### ISSUE TITLE
use fixture for lemma translations test

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#217]
it's failing on travis:

```
 ● lexicons/adapter.test.js › 4 AlpheiosLemmaTranslationsAdapter - getAvailableResLang check availablity of translations
    TypeError: Cannot read property 'forEach' of undefined
      92 | 
      93 |       let mapLangUri = {} // eslint-disable-line prefer-const
    > 94 |       unparsed.forEach(function (langItem) {
         |                ^
      95 |         mapLangUri[langItem.lang] = langItem.uri
      96 |       })
      97 | 
      at AlpheiosLemmaTranslationsAdapter._callee2$ (src/adapters/translations/adapter.js:94:16)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../../node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

```

**Comment by irina060981** [comment]
Merged and closed
